language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - pip install -e ".[test]"
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then
        py.test --doctest-modules --doctest-glob="*.rst" --ignore setup.py;
    else
        py.test;
    fi
